development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: sfjourney_development
  pool: 5
test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: sfjourney_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: sfjourney_production
  pool: 5
  username: sfjourney
  password: